cp /Users/sjo/idl/astrolib/pro/astrom/ad2xy.pro code
cp /Users/sjo/idl/cosmology/StudentCosmo/archive_software.pro code
cp /Users/sjo/idl/astrolib/pro/misc/astrolib.pro code
cp /Users/sjo/idl/astrolib/pro/fits/check_fits.pro code
cp /Users/sjo/idl/misc/colours.pro code
cp /Users/sjo/idl/astrolib/pro/image/dist_circle.pro code
cp /Users/sjo/idl/cosmology/StudentCosmo/endps.pro code
cp /Users/sjo/idl/astrolib/pro/astrom/extast.pro code
cp /Users/sjo/idl/astrolib/pro/fits_bintable/fxaddpar.pro code
cp /Users/sjo/idl/astrolib/pro/fits_bintable/fxaddpar.pro code
cp /Users/sjo/idl/astrolib/pro/fits_bintable/fxaddpar.pro code
cp /Users/sjo/idl/hermes_play/code/gauss2dfit.pro code
cp /Users/sjo/idl/astrolib/pro/astro/gcirc.pro code
cp /Users/sjo/idl/astrolib/pro/astrom/getrot.pro code
cp /Users/sjo/idl/HermesAstrom/code/hermes_fix_astrom.pro code
cp /Users/sjo/idl/astrolib/pro/astrom/hextract.pro code
cp /Users/sjo/idl/hermes_play/code/iccontour.pro code
cp /Users/sjo/idl/hermes_play/code/icplot.pro code
cp /Users/sjo/idl/hermes_play/code/icxy2ad.pro code
cp /Users/sjo/idl/astrolib/pro/plot/legend.pro code
cp /Users/sjo/idl/astrolib/pro/misc/match.pro code
cp /Users/sjo/idl/astrolib/pro/fits/mrd_hread.pro code
cp /Users/sjo/idl/astrolib/pro/misc/mrd_skip.pro code
cp /Users/sjo/idl/astrolib/pro/fits/mwrfits.pro code
cp /Users/sjo/idl/corrie/idl/my_idl_startup_pro.pro code
cp /Users/sjo/common/idl/coyoteprograms/pickcolorname.pro code
cp /Users/sjo/common/idl/coyoteprograms/pickcolorname.pro code
cp /Users/sjo/common/idl/coyoteprograms/pickcolorname.pro code
cp /Users/sjo/idl/hermes_play/code/pix_scale.pro code
cp /Users/sjo/idl/astrolib/pro/plot/plotsym.pro code
cp /Users/sjo/idl/astrolib/pro/astrom/putast.pro code
cp /Users/sjo/idl/astrolib/pro/astro/radec.pro code
cp /Users/sjo/idl/astrolib/pro/misc/remchar.pro code
cp /Users/sjo/idl/cosmology/StudentCosmo/set_plot_ps.pro code
cp /Users/sjo/idl/HermesAstrom/code/stack_image.pro code
cp /Users/sjo/idl/astrolib/pro/fits/sxaddhist.pro code
cp /Users/sjo/idl/astrolib/pro/fits/sxaddpar.pro code
cp /Users/sjo/idl/astrolib/pro/astro/ticpos.pro code
cp /Users/sjo/idl/astrolib/pro/astrom/wcssph2xy.pro code
cp /Users/sjo/idl/astrolib/pro/astrom/wcsxy2sph.pro code
cp /Users/sjo/idl/astrolib/pro/astrom/wcs_rotate.pro code
cp /Users/sjo/idl/astrolib/pro/astrom/xy2ad.pro code
cp /Users/sjo/idl/astrolib/pro/astrom/xyad.pro code
cp /Users/sjo/idl/astrolib/pro/misc/zparcheck.pro code
cp /Users/sjo/idl/astrolib/pro/astro/adstring.pro code
cp /Users/sjo/idl/hermes_play/code/curvefit.pro code
cp /Users/sjo/idl/astrolib/pro/misc/detabify.pro code
cp /Users/sjo/common/idl/coyoteprograms/error_message.pro code
cp /Users/sjo/common/idl/coyoteprograms/fsc_color.pro code
cp /Users/sjo/common/idl/coyoteprograms/fsc_color.pro code
cp /Users/sjo/common/idl/coyoteprograms/fsc_color.pro code
cp /Users/sjo/idl/astrolib/pro/fits/fxmove.pro code
cp /Users/sjo/idl/astrolib/pro/fits_bintable/fxpar.pro code
cp /Users/sjo/idl/astrolib/pro/fits/fxposit.pro code
cp /Users/sjo/idl/hermes_play/code/gauss2dfit.pro code
cp /Users/sjo/idl/hermes_play/code/gaussfit.pro code
cp /Users/sjo/idl/astrolib/pro/misc/gettok.pro code
cp /Users/sjo/idl/astrolib/pro/astrom/get_equinox.pro code
cp /Users/sjo/idl/hermes_play/code/linfit.pro code
cp /Users/sjo/idl/astrolib/pro/fits/mrdfits.pro code
cp /Users/sjo/idl/astrolib/pro/structure/mrd_struct.pro code
cp /Users/sjo/idl/astrolib/pro/fits/mwrfits.pro code
cp /Users/sjo/common/idl/coyoteprograms/pickcolorname.pro code
cp /Users/sjo/common/idl/coyoteprograms/pickcolorname.pro code
cp /Users/sjo/common/idl/coyoteprograms/pickcolorname.pro code
cp /Users/sjo/idl/hermes_play/code/poly_fit.pro code
cp /Users/sjo/idl/astrolib/pro/misc/strn.pro code
cp /Users/sjo/idl/astrolib/pro/fits/sxpar.pro code
cp /Users/sjo/idl/astrolib/pro/structure/tag_exist.pro code
cp /Users/sjo/idl/astrolib/pro/misc/valid_num.pro code
