cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/RadialDependence.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/archive_software.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/cirrange.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/colours.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/endps.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/icplot.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/legend.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/match.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/mrd_hread.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/mrd_skip.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/plotsym.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/readcol.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/remchar.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/set_plot_ps.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/star_artefacts_circle.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/star_artefacts_spike_azimuthal.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/star_artefacts_star.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/comfit.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/curvefit.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/error_message.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/fsc_color.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/fsc_color.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/fsc_color.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/fxmove.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/fxpar.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/fxposit.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/gaussfit.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/gettok.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/hist_2d.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/interpol.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/linfit.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/mrdfits.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/mrd_struct.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/poly_fit.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/star_artefacts_threshold.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/sxpar.pro code
cp /research/astrodata2/fir/HELP/dmu_products/dmu4/dmu4_sm_ELAIS-S1/idl/valid_num.pro code
